# _config.yml
title: Osama Sarfraz
description: Senior Game Developer & Game Designer
baseurl: ""
url: "https://osamasarfraz.github.io"
theme: minima

# Minima dark skin
minima:
  skin: dark

# Build settings
markdown: kramdown
permalink: pretty

# Social links (optional)
github_username: osamasarfraz